import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const context = { window: {}, console, Intl, Date, Set, Map, JSON, Number, String, Math, Object, Array, parseFloat, isNaN };
context.window = context;
vm.createContext(context);
for (const file of ['js/core.js', 'js/storage.js', 'js/parser.js', 'js/statistics.js']) vm.runInContext(fs.readFileSync(file, 'utf8'), context, { filename: file });
const core = context.FutStatsCore;
const parser = context.FutStatsParser;
const stats = context.FutStatsStatistics;
const future = { title: 'A x B', dateTime: '06/09/2099 - 16:00' };
assert.equal(core.getMatchStatus(future, new Date('2099-09-06T20:00:00Z')), 'live');
assert.equal(core.getMatchStatus(future, new Date('2099-09-06T22:00:00Z')), 'finished');
assert.equal(core.evaluatePrediction({ market: 'over_goals', line: 1.5 }, { homeGoals: 2, awayGoals: 0 }), 'green');
assert.equal(core.evaluatePrediction({ market: 'over_goals', line: 2.5 }, { homeGoals: 2, awayGoals: 0 }), 'red');
assert.equal(core.evaluatePrediction({ market: 'over_goals', line: 2 }, { homeGoals: 1, awayGoals: 1 }), 'push');
const txt = 'Flamengo x Palmeiras - [06/09/2026 - 16:00]\n\nQuantidade esperada de gols no jogo: 2,7\nMédia de escanteios: 10\n';
const parsedTxt = parser.parse(txt).matches;
assert.equal(parsedTxt.length, 1);
assert.equal(parsedTxt[0].gols, 2.7);
assert.equal(parsedTxt[0].escanteios, 10);
assert.equal(parsedTxt[0].cartoes, null);
assert.equal(parsedTxt[0].id, core.stableMatchId(parsedTxt[0]));
const zeroTxt = parser.parse('A x B - [06/09/2026 - 16:00]\\nQuantidade esperada de gols no jogo: 0\\n').matches[0];
assert.equal(zeroTxt.gols, 0);
assert.equal(zeroTxt.escanteios, null);
const json = parser.parse('[{"title":"A x B","dateTime":"06/09/2026 - 16:00","gols":2}]');
assert.equal(json.matches.length, 1);
assert.equal(json.matches[0].gols, 2);
assert.ok(json.matches[0].escanteios == null);
assert.equal(parser.parse('{bad').matches.length, 0);
const calculated = stats.calculate([{ evaluation: { status: 'green' }, odd: 2, stake: 10 }, { evaluation: { status: 'red' }, odd: 2, stake: 10 }]);
assert.equal(calculated.greens, 1);
assert.equal(calculated.profit, 0);
console.log('FutStats core tests: OK');
